/**
 * Renders an immutable certificate SVG (generated by us, inputs XML-escaped at
 * issue time) responsively. Shows a REVOKED overlay when applicable.
 */
export function CertificateView({
  svg,
  revoked = false,
  revokedLabel = "Revoked",
}: {
  svg: string;
  revoked?: boolean;
  revokedLabel?: string;
}) {
  return (
    <div className="relative">
      <div
        className="overflow-hidden rounded-lg border border-slate-200 shadow-sm [&>svg]:block [&>svg]:h-auto [&>svg]:w-full"
        // svg is generated server-side from escaped data — safe to inline.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
      {revoked && (
        <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
          <span className="-rotate-12 rounded bg-red-600/90 px-6 py-2 text-2xl font-bold uppercase tracking-widest text-white shadow">
            {revokedLabel}
          </span>
        </div>
      )}
    </div>
  );
}
