import { DEFAULT_CERTIFICATE_TEMPLATE } from "./templates";

/**
 * Built-in SEMINAR certificate template — an INTERIM placeholder.
 *
 * A seminar is a single event, so the course template's wording is wrong for
 * it: it names a fixed programme, claims the candidate "attended all 12
 * modules", and prints a list of included topics. This module derives a seminar
 * variant from the course template by rewriting exactly those lines, keeping the
 * design, fonts, artwork and QR slot identical.
 *
 * Derivation (rather than a second 145 KB inlined SVG) is deliberate: the course
 * template is machine-generated by `scripts/update-certificate-template.mjs`
 * from the designer's Illustrator file, so a hand-maintained copy would drift
 * away from the brand every time the designer hands back a new export. Deriving
 * means artwork updates land on both certificates automatically.
 *
 * WHEN THE DESIGNER SUPPLIES A DEDICATED SEMINAR SVG: drop it in, extend
 * `scripts/update-certificate-template.mjs` to emit
 * `SEMINAR_CERTIFICATE_TEMPLATE` alongside `DEFAULT_CERTIFICATE_TEMPLATE`, and
 * delete this file's derivation — `defaultTemplateFor()` in `render.ts` is the
 * only consumer, so nothing else has to change.
 *
 * Rendered layout:
 *
 *     Certificate of Completion
 *              Seminar                      <- was "Advanced Pre-/ Rehabilitation"
 *            ───────────
 *          This certifies that
 *           MAX MUSTERMANN
 *   has successfully attended the seminar   <- was three separately positioned
 *      and passed the certification test       lines with a hardcoded "12 modules"
 *          {{course_title}}
 *           {{event_date}}                  <- was {{included_topics}}
 *   [QR]              12 March 2026 / IIS-2026-A1B2
 */

/** viewBox is `0 0 841.89 595.28` (A4 landscape, pt) — this is its center. */
const CERT_CENTER_X = 420.945;

/** Course-template text this module rewrites. If the designer's SVG stops
 * containing one of these, the corresponding rewrite is skipped and the seminar
 * certificate silently falls back to the course wording for that line — which
 * `seminar-template.test.ts` asserts against, so the drift fails CI rather than
 * reaching a candidate. */
const MARKER = {
  subtitle: "Advanced Pre-/ Rehabilitation",
  sentenceStart: "has successfully attended all",
  moduleCount: "12 modules",
  sentenceEnd: "and passed the certification test",
  /** The topics row's static label, inline with the slot in the same tspan. */
  topicsLabel: "Topics covered: {{included_topics}}",
} as const;

/** Matches one complete `<text>…</text>` element (they are never nested). */
const TEXT_ELEMENT = /<text\b[^>]*>[\s\S]*?<\/text>/g;

/**
 * Replaces the first `<text>` element whose body contains `marker`. Returns the
 * SVG unchanged when no element matches, so a template shape change degrades to
 * "course wording on a seminar certificate" rather than a crash at issue time.
 */
function replaceTextElement(
  svg: string,
  marker: string,
  replacement: string,
): string {
  let done = false;
  return svg.replace(TEXT_ELEMENT, (element) => {
    if (done || !element.includes(marker)) return element;
    done = true;
    return replacement;
  });
}

/** A center-anchored `<text>` line at the certificate's horizontal center. */
function centeredLine(cssClass: string, y: number, body: string): string {
  return `<text class="${cssClass}" text-anchor="middle" transform="translate(${CERT_CENTER_X} ${y})"><tspan x="0" y="0">${body}</tspan></text>`;
}

/** Rewrites the course template's course-specific lines for a single event. */
export function deriveSeminarTemplate(courseTemplate: string): string {
  let svg = courseTemplate;

  // 1. Programme subtitle → the generic "Seminar" label. Re-anchored to center
  //    because the original is a long left-aligned string and the replacement is
  //    a short word.
  svg = replaceTextElement(
    svg,
    MARKER.subtitle,
    centeredLine("st10", 204.58, "Seminar"),
  );

  // 2. The "has successfully attended all | 12 modules | and passed the
  //    certification test" line is three separately positioned <text> elements
  //    (so the module count can be bold). A seminar has no module count, so
  //    collapse all three into one centered sentence.
  //
  //    The two trailing elements are dropped BEFORE the first is rewritten: the
  //    replacement sentence ends with the same words as MARKER.sentenceEnd, so
  //    rewriting first would make the sentence its own deletion target.
  svg = replaceTextElement(svg, MARKER.moduleCount, "");
  svg = replaceTextElement(svg, MARKER.sentenceEnd, "");
  svg = replaceTextElement(
    svg,
    MARKER.sentenceStart,
    centeredLine(
      "st6",
      341.65,
      "has successfully attended the seminar and passed the certification test",
    ),
  );

  // 3. The included-topics row sits directly under the course title and is never
  //    used by a seminar, so the slot carries the event date instead. Its static
  //    "Topics covered:" label goes with it — without this the seminar
  //    certificate reads "Topics covered: 12 March 2026".
  svg = svg.replaceAll(MARKER.topicsLabel, "{{event_date}}");
  svg = svg.replaceAll("{{included_topics}}", "{{event_date}}");
  svg = svg.replaceAll("{{topics}}", "{{event_date}}");

  return svg;
}

export const SEMINAR_CERTIFICATE_TEMPLATE = deriveSeminarTemplate(
  DEFAULT_CERTIFICATE_TEMPLATE,
);
